import { FaReact, FaDocker, FaGitAlt, FaLinux, FaGithub, FaLinkedin } from 'react-icons/fa';
import { RiNextjsFill, RiTailwindCssFill } from 'react-icons/ri';
import { SiTypescript, SiExpress, SiPostgresql, SiJest, SiVercel, SiAlwaysdata } from 'react-icons/si';
import { DiNodejs } from 'react-icons/di';
import { AiOutlineCode } from 'react-icons/ai';
import { BsCloud } from 'react-icons/bs';
import { MdOutlineMail } from 'react-icons/md';
import { IoDocumentTextSharp } from 'react-icons/io5';

export const IconReact = FaReact;
export const IconDocker = FaDocker;
export const IconGit = FaGitAlt;
export const IconLinux = FaLinux;
export const IconGithub = FaGithub;
export const IconLinkedin = FaLinkedin;
export const IconNextjs = RiNextjsFill;
export const IconTailwindCSS = RiTailwindCssFill;
export const IconTypeScript = SiTypescript;
export const IconExpress = SiExpress;
export const IconPostgreSQL = SiPostgresql;
export const IconJest = SiJest;
export const IconVercel = SiVercel;
export const IconAlwaysdata = SiAlwaysdata;
export const IconNodejs = DiNodejs;
export const IconCode = AiOutlineCode;
export const IconCloud = BsCloud;
export const IconEmail = MdOutlineMail;
export const IconDocument = IoDocumentTextSharp;
